export const DESTINATIONS = [
  {
    abbreviation: "ADB",
    expansion: "Izmir",
    country: "Turcja",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "AGP",
    expansion: "Malaga",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "AHO",
    expansion: "Alghero",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "ALC",
    expansion: "Alicante",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "ATH",
    expansion: "Ateny",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "AYT",
    expansion: "Antalya",
    country: "Turcja",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "BGY",
    expansion: "Mediolan Bergamo",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "BJV",
    expansion: "Bodrum",
    country: "Turcja",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "BOJ",
    expansion: "Burgas",
    country: "Bułgaria",
    zone: "Schengen",
  },
  {
    abbreviation: "BRI",
    expansion: "Bari",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "CFU",
    expansion: "Korfu",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "CHQ",
    expansion: "Chania",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "CTA",
    expansion: "Katania",
    country: "Włochy (Sycylia)",
    zone: "Schengen",
  },
  {
    abbreviation: "DLM",
    expansion: "Dalaman",
    country: "Turcja",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "DTM",
    expansion: "Dortmund",
    country: "Niemcy",
    zone: "Schengen",
  },
  {
    abbreviation: "DUB",
    expansion: "Dublin",
    country: "Irlandia",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "EFL",
    expansion: "Kefalonia",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "FAO",
    expansion: "Faro",
    country: "Portugalia",
    zone: "Schengen",
  },
  {
    abbreviation: "FCO",
    expansion: "Rzym Fumicino",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "FRL",
    expansion: "Forli",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "FUE",
    expansion: "Fuerteventura",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "GPA",
    expansion: "Patras",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "HER",
    expansion: "Heraklion",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "HRG",
    expansion: "Hurghada",
    country: "Egipt",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "KGS",
    expansion: "Kos",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "KVA",
    expansion: "Kavala",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "LCA",
    expansion: "Larnaca",
    country: "Cypr",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "MAH",
    expansion: "Menorka",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "MAN",
    expansion: "Manchester",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "MLA",
    expansion: "Malta",
    country: "Malta",
    zone: "Schengen",
  },
  {
    abbreviation: "OSL",
    expansion: "Oslo Gardermoen",
    country: "Norwegia",
    zone: "Schengen",
  },
  {
    abbreviation: "PFO",
    expansion: "Pafos",
    country: "Cypr",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "PMI",
    expansion: "Palma De Mallorca",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "PUY",
    expansion: "Pula",
    country: "Chorwacja",
    zone: "Schengen",
  },
  {
    abbreviation: "PVK",
    expansion: "Preweza Leukada",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "RHO",
    expansion: "Rodos",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "SKG",
    expansion: "Saloniki",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "STN",
    expansion: "Londyn Stansted",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "TIA",
    expansion: "Tirana",
    country: "Albania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "TPS",
    expansion: "Trapani",
    country: "Włochy (Sycylia)",
    zone: "Schengen",
  },
  {
    abbreviation: "TSF",
    expansion: "Wenecja Treviso",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "VAR",
    expansion: "Varna",
    country: "Bułgaria",
    zone: "Schengen",
  },
  {
    abbreviation: "ZAD",
    expansion: "Zadar",
    country: "Chorwacja",
    zone: "Schengen",
  },
  {
    abbreviation: "ZTH",
    expansion: "Zakynthos",
    country: "Grecja",
    zone: "Schengen",
  },
];
