export const DEST_KTW = [
  {
    abbreviation: "ADB",
    expansion: "Izmir",
    country: "Turcja",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "AGP",
    expansion: "Malaga",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "AHO",
    expansion: "Alghero",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "ALC",
    expansion: "Alicante",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "ATH",
    expansion: "Ateny",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "AYT",
    expansion: "Antalya",
    country: "Turcja",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "BGY",
    expansion: "Mediolan Bergamo",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "BJV",
    expansion: "Bodrum",
    country: "Turcja",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "BOJ",
    expansion: "Burgas",
    country: "Bułgaria",
    zone: "Schengen",
  },
  {
    abbreviation: "BRI",
    expansion: "Bari",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "CFU",
    expansion: "Korfu",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "CHQ",
    expansion: "Chania",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "CRL",
    expansion: "Bruksela - Charleroi",
    country: "Belgia",
    zone: "Schengen",
  },
  {
    abbreviation: "CTA",
    expansion: "Katania",
    country: "Włochy (Sycylia)",
    zone: "Schengen",
  },
  {
    abbreviation: "DBV",
    expansion: "Dubrownik",
    country: "Chorwacja",
    zone: "Schengen",
  },
  {
    abbreviation: "DLM",
    expansion: "Dalaman",
    country: "Turcja",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "DTM",
    expansion: "Dortmund",
    country: "Niemcy",
    zone: "Schengen",
  },
  {
    abbreviation: "DUB",
    expansion: "Dublin",
    country: "Irlandia",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "EFL",
    expansion: "Kefalonia",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "FAO",
    expansion: "Faro",
    country: "Portugalia",
    zone: "Schengen",
  },
  {
    abbreviation: "FCO",
    expansion: "Rzym Fumicino",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "FRL",
    expansion: "Forli",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "FUE",
    expansion: "Fuerteventura",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "GPA",
    expansion: "Patras",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "HER",
    expansion: "Heraklion",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "HRG",
    expansion: "Hurghada",
    country: "Egipt",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "KGS",
    expansion: "Kos",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "KVA",
    expansion: "Kavala",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "LCA",
    expansion: "Larnaca",
    country: "Cypr",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "MAH",
    expansion: "Menorka",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "MAN",
    expansion: "Manchester",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "MLA",
    expansion: "Malta",
    country: "Malta",
    zone: "Schengen",
  },
  {
    abbreviation: "OSL",
    expansion: "Oslo Gardermoen",
    country: "Norwegia",
    zone: "Schengen",
  },
  {
    abbreviation: "PFO",
    expansion: "Pafos",
    country: "Cypr",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "PMI",
    expansion: "Palma De Mallorca",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "PUY",
    expansion: "Pula",
    country: "Chorwacja",
    zone: "Schengen",
  },
  {
    abbreviation: "PVK",
    expansion: "Preweza Leukada",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "RHO",
    expansion: "Rodos",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "SKG",
    expansion: "Saloniki",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "STN",
    expansion: "Londyn Stansted",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "TIA",
    expansion: "Tirana",
    country: "Albania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "TPS",
    expansion: "Trapani",
    country: "Włochy (Sycylia)",
    zone: "Schengen",
  },
  {
    abbreviation: "TSF",
    expansion: "Wenecja Treviso",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "VAR",
    expansion: "Varna",
    country: "Bułgaria",
    zone: "Schengen",
  },
  {
    abbreviation: "ZAD",
    expansion: "Zadar",
    country: "Chorwacja",
    zone: "Schengen",
  },
  {
    abbreviation: "ZTH",
    expansion: "Zakynthos",
    country: "Grecja",
    zone: "Schengen",
  },
];

export const DEST_KRK = [
  {
    abbreviation: "AGA",
    expansion: "Agadir",
    country: "Maroko",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "AGP",
    expansion: "Malaga",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "ALC",
    expansion: "Alicante",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "AMM",
    expansion: "Amman",
    country: "Jordania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "AOI",
    expansion: "Ankona",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "ARN",
    expansion: "Sztokholm Arlanda",
    country: "Szwecja",
    zone: "Schengen",
  },
  {
    abbreviation: "ATH",
    expansion: "Ateny",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "AYT",
    expansion: "Antalya",
    country: "Turcja",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "BCN",
    expansion: "Barcelona - El Prat",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "BER",
    expansion: "Berlin Brandenburg",
    country: "Niemcy",
    zone: "Schengen",
  },
  {
    abbreviation: "BFS",
    expansion: "Belfast",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "BGY",
    expansion: "Milan Bergamo",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "BHX",
    expansion: "Birmingham",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "BLL",
    expansion: "Billund",
    country: "Dania",
    zone: "Schengen",
  },
  {
    abbreviation: "BLQ",
    expansion: "Bologna",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "BOD",
    expansion: "Bordeaux",
    country: "Francja",
    zone: "Schengen",
  },
  {
    abbreviation: "BOH",
    expansion: "Bournemouth",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "BOJ",
    expansion: "Burgas",
    country: "Bułgaria",
    zone: "Schengen",
  },
  {
    abbreviation: "BRI",
    expansion: "Bari",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "BRS",
    expansion: "Bristol",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "BVA",
    expansion: "Paryż - Beauvais",
    country: "Francja",
    zone: "Schengen",
  },
  {
    abbreviation: "CAG",
    expansion: "Cagliari",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "CFU",
    expansion: "Korfu",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "CHQ",
    expansion: "Chania",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "CIA",
    expansion: "Rzym - Ciampino",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "CPH",
    expansion: "Kopenhaga",
    country: "Dania",
    zone: "Schengen",
  },
  {
    abbreviation: "CRL",
    expansion: "Bruksela - Charleroi",
    country: "Belgia",
    zone: "Schengen",
  },
  {
    abbreviation: "CTA",
    expansion: "Katania",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "DBV",
    expansion: "Dubrownik",
    country: "Chorwacja",
    zone: "Schengen",
  },
  {
    abbreviation: "DTM",
    expansion: "Dortmund",
    country: "Niemcy",
    zone: "Schengen",
  },
  {
    abbreviation: "DUB",
    expansion: "Dublin",
    country: "Irlandia",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "EDI",
    expansion: "Edynburg",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "EIN",
    expansion: "Eindhoven",
    country: "Holandia",
    zone: "Schengen",
  },
  {
    abbreviation: "EMA",
    expansion: "East Midlands",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "ETM",
    expansion: "Eilat (Ramon)",
    country: "Izrael",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "FAO",
    expansion: "Faro",
    country: "Portugalia",
    zone: "Schengen",
  },
  {
    abbreviation: "FMM",
    expansion: "Memmingen",
    country: "Niemcy",
    zone: "Schengen",
  },
  {
    abbreviation: "FUE",
    expansion: "Fuerteventura",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "GDN",
    expansion: "Gdańsk",
    country: "Polska",
    zone: "Schengen",
  },
  {
    abbreviation: "GLA",
    expansion: "Glasgow",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "GOT",
    expansion: "Goteborg",
    country: "Szwecja",
    zone: "Schengen",
  },
  {
    abbreviation: "GRO",
    expansion: "Barcelona - Girona",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "JTR",
    expansion: "Santorini",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "LBA",
    expansion: "Leeds Bradford",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "LDE",
    expansion: "Lourdes",
    country: "Francja",
    zone: "Schengen",
  },
  {
    abbreviation: "LIL",
    expansion: "Lille",
    country: "Francja",
    zone: "Schengen",
  },
  {
    abbreviation: "LIS",
    expansion: "Lizbona",
    country: "Portugalia",
    zone: "Schengen",
  },
  {
    abbreviation: "LPA",
    expansion: "Gran Canaria",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "LPL",
    expansion: "Liverpool",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "LTN",
    expansion: "Londyn - Luton",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "MAD",
    expansion: "Madryt",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "MAN",
    expansion: "Manchester",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "MLA",
    expansion: "Malta",
    country: "Malta",
    zone: "Schengen",
  },
  {
    abbreviation: "MRS",
    expansion: "Marsylia",
    country: "Francja",
    zone: "Schengen",
  },
  {
    abbreviation: "NAP",
    expansion: "Neapol",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "NCL",
    expansion: "Newcastle",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "NUE",
    expansion: "Norymberga",
    country: "Niemcy",
    zone: "Schengen",
  },
  {
    abbreviation: "OLB",
    expansion: "Olbia",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "OPO",
    expansion: "Porto",
    country: "Portugalia",
    zone: "Schengen",
  },
  {
    abbreviation: "PEG",
    expansion: "Perugia",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "PFO",
    expansion: "Paphos",
    country: "Cypr",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "PMI",
    expansion: "Palma de Mallorca",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "PMO",
    expansion: "Palermo",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "POZ",
    expansion: "Poznań",
    country: "Polska",
    zone: "Schengen",
  },
  {
    abbreviation: "PRG",
    expansion: "Praga",
    country: "Czechy",
    zone: "Schengen",
  },
  {
    abbreviation: "PSA",
    expansion: "Pisa",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "PSR",
    expansion: "Pescara",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "RHO",
    expansion: "Rodos",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "RIX",
    expansion: "Ryga",
    country: "Łotwa",
    zone: "Schengen",
  },
  {
    abbreviation: "RMI",
    expansion: "Rimini",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "SKG",
    expansion: "Saloniki",
    country: "Grecja",
    zone: "Schengen",
  },
  {
    abbreviation: "SNN",
    expansion: "Shannon",
    country: "Irlandia",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "STN",
    expansion: "Londyn - Stansted",
    country: "Wielka Brytania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "SUF",
    expansion: "Lamezia",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "SVQ",
    expansion: "Sewilla",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "SZY",
    expansion: "Olsztyn - Mazury",
    country: "Polska",
    zone: "Schengen",
  },
  {
    abbreviation: "SZZ",
    expansion: "Szczecin",
    country: "Polska",
    zone: "Schengen",
  },
  {
    abbreviation: "TFS",
    expansion: "Teneryfa Południowa",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "TGD",
    expansion: "Podgorica",
    country: "Czarnogóra",
    zone: "Schengen",
  },
  {
    abbreviation: "TIA",
    expansion: "Tirana",
    country: "Albania",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "TLS",
    expansion: "Tuluza",
    country: "Francja",
    zone: "Schengen",
  },
  {
    abbreviation: "TLV",
    expansion: "Tel Aviv",
    country: "Izrael",
    zone: "Non-Schengen",
  },
  {
    abbreviation: "TRF",
    expansion: "Oslo - Torp",
    country: "Norwegia",
    zone: "Schengen",
  },
  {
    abbreviation: "TRN",
    expansion: "Turyn",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "TRS",
    expansion: "Triest",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "TSF",
    expansion: "Wenecja Treviso",
    country: "Włochy",
    zone: "Schengen",
  },
  {
    abbreviation: "VAR",
    expansion: "Warna",
    country: "Bułgaria",
    zone: "Schengen",
  },
  {
    abbreviation: "VIE",
    expansion: "Wiedeń",
    country: "Austria",
    zone: "Schengen",
  },
  {
    abbreviation: "VLC",
    expansion: "Walencja",
    country: "Hiszpania",
    zone: "Schengen",
  },
  {
    abbreviation: "ZAD",
    expansion: "Zadar",
    country: "Chorwacja",
    zone: "Schengen",
  },
];
